import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Formdata from '../pages/formdata'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>ReStork Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 style={{fontFamily: " 'Russo One', sans-serif ",fontSize: '40px'}}>Deliver all the Customer Refund Items Today</h1>
        <br></br>
        <Formdata />
        <br></br>
        <h1 style={{fontFamily: " 'Russo One', sans-serif  ", color: "white"}}  >Hurry Up </h1>
        <br></br>
        <h1 style={{border: "3px solid white", color: "white", padding: "10px"}}>All rights reserved by ReStork </h1>
      </main>
    </>
  )
}
